ITinTheDWebSite/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ITinTheDWebSite.Controllers
{
    public class AboutController : Controller
    {
        //
        // GET: /About/

        public ActionResult Index()
        {
            return View();
        }

    }
}

ITinTheDWebSite/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ITinTheDWebSite.Controllers
{
    public class ContactController : Controller
    {
        //
        // GET: /Contact/

        public ActionResult Index()
        {
            return View();
        }

    }
}

ITinTheDWebSite/Controllers/EmailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Mail;
using sbContact.Models;
using System.Configuration;



namespace sbContact.Controllers
{
    public class EmailController : Controller
    {
        //
        // GET: /Email/

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Sendit(EmailFields Mailer)
        {

            MailMessage email = new MailMessage
            {
                Sender = new MailAddress(Mailer.Email),
                Subject = Mailer.Subject,
                Body = Mailer.Message
            };
            //email.To.Add(new MailAddress("whover.@whatver.com"));
            email.To.Add(System.Configuration.ConfigurationManager.AppSettings["EmailTo"].ToString());
            SmtpClient client = new SmtpClient();
            //client.Credentials = new NetworkCredential(username, password);
            client.Send(email);
            return View();
        }

    }
}

ITinTheDWebSite/Views/Shared/_BootstrapLayout1.cshtml
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <title>ITinTheD</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
 
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
 
    <!-- Le styles -->
    <link href="/Content/themes/bootstrap.min.css" rel="stylesheet"/>
    <link href="/Content/themes/bootstrap-responsive.min.css" rel="stylesheet"/>
    <link href="/../css/docs.css" rel="stylesheet">
 
	 <script type="text/javascript">

	     var _gaq = _gaq || [];
	     _gaq.push(['_setAccount', 'UA-23019901-1']);
	     _gaq.push(['_setDomainName', "bootswatch.com"]);
	     _gaq.push(['_setAllowLinker', true]);
	     _gaq.push(['_trackPageview']);

	     (function () {
	         var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	         ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	         var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	     })();
 
	 </script>
 
  </head>
 
  <body class="preview" data-spy="scroll" data-target=".subnav" data-offset="80">
    <script src="../js/bsa.js"></script>
 
 
  <!-- Navbar
    ================================================== -->
 <div class="navbar navbar-fixed-top">
   <div class="navbar-inner">
     <div class="container">
       <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </a>
       <a class="brand" href="../">Bienvenue Sur IT a Detroit</a>
       <div class="nav-collapse" id="main-menu">
 
       </div>
     </div>
   </div>
 </div>
 
    <div class="container">
 
 
<!-- Masthead
================================================== -->
<header class="jumbotron subhead" id="overview">
  <div class="row">
    <div class="span6">
      <h1>Homepage</h1>
      <p class="lead">Our Mission Statement.</p>
    </div>
    <div class="span6">
      <div class="bsa well">
          <div id="bsap_1277971" class="bsarocks bsap_c466df00a3cd5ee8568b5c4983b6bb19"></div>
          <div class="clearfix"><a href="http://adpacks.com" id="bsap_aplink">via Ad Packs</a></div>
      </div>
    </div>
  </div>
  <div class="subnav">
    <ul class="nav nav-pills">
      <li>@Html.ActionLink("Home","Index", "Home")</li>
      <li>@Html.ActionLink("About Us","Index", "About")</li>
      <li><a href="#buttons">Registration</a></li>
      <li><a href="#forms">What's hot in the D</a></li>
      <li><a href="#miscellaneous">Succes Stories</a></li>
    </ul>
  </div>
</header>
@RenderBody()
 
 
<!-- Typography
================================================== -->
<section id="Homepage">
  <div class="page-header">
    <h1>Homepage</h1>
  </div>
 
  <!-- Headings & Paragraph Copy -->
  <div class="row">
 
    <div class="span4">
      <div class="well">
        <h1>h1. Heading 1</h1>
        <h2>h2. Heading 2</h2>
        <h3>h3. Heading 3</h3>
        <h4>h4. Heading 4</h4>
        <h5>h5. Heading 5</h5>
        <h6>h6. Heading 6</h6>
      </div>
    </div>
 
    <div class="span4">
      <h3>Example body text</h3>
      <p>Nullam quis risus eget urna mollis ornare vel eu leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
      <p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Donec sed odio dui.</p>
    </div>
 
    <div class="span4">
      <h3>Example addresses</h3>
      <address>
        <strong>Twitter, Inc.</strong><br>
        795 Folsom Ave, Suite 600<br>
        San Francisco, CA 94107<br>
        <abbr title="Phone">P:</abbr> (123) 456-7890
      </address>
      <address>
        <strong>Full Name</strong><br>
        <a href="mailto:#">first.last@gmail.com</a>
      </address>
    </div>
 
  </div>
 
</section>
 
 
<!-- Navbar
================================================== -->
<section id="About Us">
  <div class="page-header">
    <h1>About Us</h1>
  </div>
  <div class="navbar">
    <div class="navbar-inner">
      <div class="container" style="width: auto;">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">Project name</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
              </ul>
            </li>
          </ul>
          <form class="navbar-search pull-left" action="">
            <input type="text" class="search-query span2" placeholder="Search">
          </form>
          <ul class="nav pull-right">
            <li><a href="#">Link</a></li>
            <li class="divider-vertical"></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.nav-collapse -->
      </div>
    </div><!-- /navbar-inner -->
  </div><!-- /navbar -->
 
  <div class="navbar navbar-inverse">
    <div class="navbar-inner">
      <div class="container" style="width: auto;">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">Project name</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
              </ul>
            </li>
          </ul>
          <form class="navbar-search pull-left" action="">
            <input type="text" class="search-query span2" placeholder="Search">
          </form>
          <ul class="nav pull-right">
            <li><a href="#">Link</a></li>
            <li class="divider-vertical"></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.nav-collapse -->
      </div>
    </div><!-- /navbar-inner -->
  </div><!-- /navbar -->
 
</section>
 
 
    
<!-- Labels
================================================== -->
 
 
     <!-- Footer
      ================================================== -->
      <footer class="footer">
        <p class="pull-right"><a href="#">Back to top</a></p>
      </footer>
 
    </div><!-- /container -->
 
 
 
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script src="../js/bootstrap.min.js"></script>
    <script src="../js/application.js"></script>
    <script src="../js/bootswatch.js"></script>
 
 
  </body>
</html>

ITinTheDWebSite/Views/Shared/_ErrorReport.cshtml
@model sbContact.Models.EmailFields
 
<!-- Modal -->
 
    <!-- Button to trigger modal -->
    <a href="#ErrorModal" style="color:Black"  role="button" class="btn" data-toggle="modal">[+] Feedback</a>
 
 
<div id="ErrorModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myErrorLabel" aria-hidden="true" style="width:400px; height:450px;">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 id="myErrorLabel">Feedback for IT in the D</h4>
    </div>
 
    @using (Html.BeginForm("Sendit","Email")) {
        @Html.ValidationSummary(true)
        <div class="well">
        <fieldset>
            <legend>Please provide the following information</legend>
            <div class="editor-label">
                @Html.LabelFor(model => model.Name)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
 
            <div class="editor-label">
                @Html.LabelFor(model => model.Email)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
   
        <div class="editor-label">
            @Html.LabelFor(model => model.Subject)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Subject)
            @Html.ValidationMessageFor(model => model.Subject)
        </div>
 
        <div class="editor-label">
            @Html.LabelFor(model => model.Message)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Message)
            @Html.ValidationMessageFor(model => model.Message)
        </div>
 
        <p>
            <input type="submit" value="Send email" />
        </p>
 
        </fieldset>
 </div>
    }
 
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ITinTheDWebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>IT in the D</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/bootstrap.css")
    @Styles.Render("~/Content/bootswatch")
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
    <script type="text/javascript" src="@Url.Content("~/Scripts/modernizr-2.6.2.js")"></script>
    <link href="/Content/bootstrap-responsive.css" rel="Stylesheet" />

    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-41739233-1', 'mitic.net');
        ga('send', 'pageview');

</script>
</head>
<body class="preview" data-spy="scroll" data-target=".subnav" data-offset="100">
    <div class="container">
    <header id="overview">
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class=""container">
                    <a data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a href="~/Home" class="brand">
                        <img src="../../Images/Carousel/ITintheD_logo.png" alt="img" /></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About Us", "Index", "About")</li>
                            <li>@Html.ActionLink("FAQ", "Index", "FAQ")</li>
                            <li>@Html.ActionLink("Sponsors", "Index", "Sponsors")</li>
                            <li class="dropdown"><a data-toggle="dropdown" class="dropdown-toggle" href="#">More
                                <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Alumni", "Index", "GraduateStudents")</li>
                                    <li>@Html.ActionLink("Academic Institutions", "Index", "AcademicInstitution")</li>
                                    <li>@Html.ActionLink("Trainers", "Index", "Trainers")</li>
                                    <li>@Html.ActionLink("Curriculum", "Index", "Curriculum")</li>
                                    <li>@Html.ActionLink("Events", "Index", "Events")</li>
                                    <li>@Html.ActionLink("News", "Index", "News")</li>
                                    <li>@Html.ActionLink("Contact Us", "Index", "Contact")</li>
                                </ul>
                            </li>
                        </ul>
                        <div class="pull-right">
                            <section id="login">
                                @Html.Partial("_LoginPartial")
                            </section>
                        </div>
                    </div>
                </div>
                            <!-- /.nav-collapse -->
            </div>
                <!-- /navbar-inner -->
                <!-- /search box powered by google cse -->
                <div class="pull-right" id="cse-search-form" style="width: 40%; position:absolute; right:0px;">Loading</div>
                    <script src="http://www.google.com/jsapi" type="text/javascript"></script>
                    <script type="text/javascript">
                        google.load('search', '1', { language: 'en', style: google.loader.themes.V2_DEFAULT });
                        google.setOnLoadCallback(function () {
                        var customSearchOptions = {}; var customSearchControl = new google.search.CustomSearchControl(
                        '006072065711276741272:zgvsbzocwco', customSearchOptions);
                        customSearchControl.setResultSetSize(google.search.Search.FILTERED_CSE_RESULTSET);
                        var options = new google.search.DrawOptions();
                        options.enableSearchboxOnly("http://www.google.com/cse?cx=006072065711276741272:zgvsbzocwco");
                        customSearchControl.draw('cse-search-form', options);
                        }, true);
                </script>
                <style type="text/css">
                    input.gsc-input, .gsc-input-box, .gsc-input-box-hover, .gsc-input-box-focus {
                    border-color: #D9D9D9;
                }
                    input.gsc-search-button, input.gsc-search-button:hover, input.gsc-search-button:focus {
                    border-color: #2F5BB7;
                    background-color: #357AE8;
                    background-image: none;
                    filter: none;
                }</style>
        </div>
        <br />

    </header>
        @RenderBody()
        <!-- Footer ================================================== -->
        <footer class="footer">
            <div class="row">
                <h4 class="span12">Our Sponsors:</h4>
            </div>
            <div class="row sponsors">
                <div class="span2 offset1 sponsor">
                    <a href="http://www.quickenloans.com/" target="_blank"><img src="../../Images/Footer/quicken_logo2.jpg" alt="quicken loans" height="24" width="124" /></a>
                </div>
                <div class="span2 sponsor">
	                <a href="http://www.compuware.com/" target="_blank"><img src="../../Images/Footer/compuwarelogosmall.png" alt="compuware" /></a>
                </div>
                <div class="span2 sponsor">
	                <a href="http://www.fathead.com/" target="_blank"><img src="../../Images/Footer/fathead2.png" alt="fathead" /></a>
                </div>
                <div class="span2 sponsor">
	                <a href="http://www.galaxesolutions.com/" target="_blank"><img src="../../Images/Footer/galaxe2.gif" alt="galaxe solutions" /></a>
                </div>
                <div class="span2 sponsor">
                    <a href="http://marketingassociates.com/" target="_blank"><img src="../../Images/Footer/mrktg_assoc_logo2.jpg" alt="marketing associates" /></a>
                </div>
            </div>
            <div class="row">
                <div class="span5">
                    <h6>Follow us on:</h6>
                    <a href="http://www.facebook.com/ITinDetroit" target="_blank">
                        <img src="../../images/facebook_icon.png" height="40" width="40" alt="facebook" /></a>
                    <a href="http://www.twitter.com/ITinDetroit" target="_blank">
                        <img src="../../Images/twitter_icon.png" height="40" width="40" alt="twitter" /></a>
                    <a href=" http://www.linkedin.com/groups/IT-in-D-Your-Detroit-4471137?itemaction=mclk&anetid=4471137&impid=4471137-4685117&pgkey=anet_about_guest&actpref=anet_about-gbm&trk=anet_about-gbm-group&goback=%2Eanb_4685117_*2_*1_*1_*1_*1_*1"
                        target="_blank">
                        <img src="../../Images/linkedin_icon.png" height="40" width="40" alt="linked in" /></a>
                    <br />
                    <a href="#">Back to top</a>
                </div>
                <div class="span6">
                    <div class="pull-right">
                        <br>
                        @Html.Partial("_ErrorReport", new sbContact.Models.EmailFields())
                        <br />
                        &copy; 2013 IT in the D
                        <br />
                        <a href="../Home/DisplayPrivacy">Privacy</a> · <a href="../Home/DisplayTerms">Terms</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
</body>
</html>